/*
** EPITECH PROJECT, 2018
** my_world
** File description:
** engine_const.c
*/

#ifndef ENGINE_CONST_H_
	#define ENGINE_CONST_H_

#include	"engine.h"

static const int	faces_order[F_TOTAL][4] = {
	{ P_TOP_BACK_LEFT, P_TOP_BACK_RIGHT,
		P_TOP_FRONT_RIGHT, P_TOP_FRONT_LEFT },
	{ P_DOWN_BACK_LEFT, P_DOWN_BACK_RIGHT,
		P_DOWN_FRONT_RIGHT, P_DOWN_FRONT_LEFT },
	{ P_TOP_BACK_LEFT, P_TOP_BACK_RIGHT,
		P_DOWN_BACK_RIGHT, P_DOWN_BACK_LEFT },
	{ P_TOP_FRONT_LEFT, P_TOP_FRONT_RIGHT,
		P_DOWN_FRONT_RIGHT, P_DOWN_FRONT_LEFT },
	{ P_TOP_FRONT_LEFT, P_TOP_BACK_LEFT,
		P_DOWN_BACK_LEFT, P_DOWN_FRONT_LEFT },
	{ P_TOP_FRONT_RIGHT, P_TOP_BACK_RIGHT,
		P_DOWN_BACK_RIGHT, P_DOWN_FRONT_RIGHT }
};


#endif /* !ENGINE_CONST_H_ */
